name: Build Noun Parser

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install g++
      run: choco install mingw

    - name: Compile Noun Parser
      run: g++ main.cpp res/noun_parser.o -o noun_parser.exe

    - name: Upload .exe as artifact
      uses: actions/upload-artifact@v4
      with:
        name: noun_parser
        path: noun_parser.exe
